spring.application.name=btgpactual

#MongoDB
spring.data.mongodb.authentication-database=${MONGODB_AUTH_DB:admin}
spring.data.mongodb.auto-index-creation=${MONGODB_AUTO_INDEX:true}
spring.data.mongodb.host=${MONGODB_HOST:localhost}
spring.data.mongodb.port=${MONGODB_PORT:27017}
spring.data.mongodb.database=${MONGODB_DB:btgpactualdb}
spring.data.mongodb.username=${MONGODB_USERNAME:admin}
spring.data.mongodb.password=${MONGODB_PASSWORD:123457}

#RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
